## Introduction: What is portfolio optimization?
Portfolio optimization is a crucial process for anyone who wants to maximize returns from their investments. 
Investments are usually a collection of so-called assets (stock, credits, bonds, derivatives, calls, puts, etc..) and this collection of assets is called a **portfolio**. 
<center><img src="ex1-01.png" width="270"></center>
The goal of portfolio optimization is to minimize risks (financial loss) and maximize returns (financial gain). But this process is not as simple as it may seem. Gaining high returns with little risk is indeed too good to be true. Risks and returns usually have a trade-off relationship which makes optmizing your portfolio a little more complicated. As Dr. Harry Markowitz states in his Moderbn Portfolio Theory he created in 1952,  "risk is an inherrent part of higher reward."

## Stock Portfolio Optimization Problem

Let us consider a portfolio optimization problem where you have a total of four assets (e.g. STOCK0, STOCK1, STOCK2, STOCK3) to choose from. Your goal is to find out a combination of two assets that will minimize the tradeoff between risk and return which is the same as finding the efficient frontier for the given risk. 

## Predefined Configuration

In [18]:
file_path = 'data/stocks_data.csv'
tickers=["AAPL", "AMZN", "GOOG", "MSFT", "TSLA"]
risk_factor =0.5 #recommend
num_assets = len(tickers)
budget = num_assets // 2  # set budget

## Import Library

In [19]:

# import pandas as pd
# import numpy as np
from helper import pretty_print_result
from qameloptimzer import qaoa_optimize, vqe_optimize, classical_optimizer
from mean_variance import MeanVarianceModel
from qamelpo import PortfolioOptimization

### Preprocessing with Mean Variance Model (Problem definition Model of Portfolio Optimization)

In [20]:

model = MeanVarianceModel(file_path=file_path, stock_names=tickers)
model.load_and_clean_data()
model.calculate_daily_returns()  # Calculate daily returns
model.calculate_mean_and_covariance()  # Calculate mean and covariance
mean_returns = model.get_mean_returns()
covariance_matrix = model.get_covariance_matrix()
# budget = 1  # Total proportion of investment

### Turning Mean Variance into Quadratic Program in order to perform optimization in Quantum

In [21]:


portfolio = PortfolioOptimization(
    expected_returns=mean_returns,
    covariances=covariance_matrix,
    risk_factor=risk_factor,
    budget=budget,
    
)

# Optmization Section

In [22]:

result = classical_optimizer(portfolio)

pretty_print_result(result,portfolio)

Optimal: selection [1. 0. 0. 0. 1.], value -0.0021

----------------- Full result ---------------------
selection	value		probability
---------------------------------------------------
[1 0 0 0 1]	-0.0021		1.0000


## Solution using QAOA

In [23]:

result = qaoa_optimize(portfolio)
pretty_print_result(result,portfolio)

## Solution using VQE

In [ ]:
result = vqe_optimize(portfolio)
pretty_print_result(result,portfolio)

Optimal: selection [1. 0. 0. 0. 1.], value -0.0021

----------------- Full result ---------------------
selection	value		probability
---------------------------------------------------
[1 1 0 0 0]	-0.0002		0.3281
[0 0 1 1 0]	-0.0005		0.1719
[1 0 0 1 0]	-0.0009		0.1484
[0 1 0 1 0]	-0.0000		0.1309
[1 0 1 0 0]	-0.0007		0.0850
[0 1 1 0 0]	0.0002		0.0713
[1 0 0 0 0]	-0.0008		0.0098
[1 0 1 1 0]	-0.0005		0.0098
[1 1 0 0 1]	-0.0011		0.0068
[0 0 0 1 1]	-0.0020		0.0059
[0 0 0 0 0]	0.0000		0.0049
[1 1 0 1 0]	0.0000		0.0049
[0 1 1 1 1]	-0.0001		0.0049
[0 1 1 1 0]	0.0004		0.0049
[1 0 0 0 1]	-0.0021		0.0029
[0 0 0 1 0]	-0.0006		0.0029
[1 0 1 0 1]	-0.0017		0.0020
[1 0 0 1 1]	-0.0018		0.0020
[1 1 0 1 1]	-0.0003		0.0020
[0 0 1 0 1]	-0.0018		0.0010
